# Default values for telegraf-daemonset.
# This is a YAML-formatted file.
## influxdb image version
## ref: https://hub.docker.com/r/library/telegraf/tags/
##
image:
  repo: "telegraf"
  tag: "1.1.0-alpine"
  pullPolicy: IfNotPresent
  

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 1

## Configure the service
service:
  type: NodePort

## Exposed telegraf configuration
## For full list of possible values see `all-config-values.yaml` and `all-config-values.toml`
## ref: https://docs.influxdata.com/telegraf/v1.1/administration/configuration/
##
config:
  agent:
    interval: "1s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: ""
    omit_hostname: false
  outputs:
    influxdb:
      urls:
        - "http://influxdb.tick:8086"
      database: "telegraf"
  inputs:
    influxdb:
      urls:
        - "http://influxdb.tick:8086/debug/vars"
        - "http://test-influxdb.influxdb:8086/debug/vars"
      timeout: "5s"
    statsd:
      service_address: ":8125"
      percentiles: 
        - 50
        - 90
        - 95
        - 99
      metric_separator: "_"
      allowed_pending_messages: 10000
      percentile_limit: 1000